DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
INFO:root:[Errno 2] No such file or directory: '/Users/kjk/src/go/src/github.com/ravendb/ravendb-go-client/python_tests\\2bad18145a2f702371d0f826decebb26.raven-topology'
DEBUG:root:('Failed to retrieve database topology from all known nodes', [('http://localhost:8080', ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /topology?name=PyRavenDB (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b856f98>: Failed to establish a new connection: [Errno 61] Connection refused',))",),))])
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /topology?name=PyRavenDB HTTP/1.1" 503 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /topology?name=PyRavenDB HTTP/1.1" 503 None
DEBUG:root:Database PyRavenDB does not exists
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8080 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /topology?name=PyRavenDB HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:9999 "GET /databases/PyRavenDB/docs?&id=foos%2F1 HTTP/1.1" 404 0
